[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pta-learn"
version = "1.0.2"
description = "A Python library for automated Pressure Transient Analysis (PTA) workflows. It provides tools for PTA flow regime feature extraction, time-lapse pattern recognition, pressure transient identification, and Bourdet derivative calculation."
readme = "README.md"
authors = [
    { name = "V. Starikov", email = "starikovv98@gmail.com" },
    { name = "B. Cui", email = "boyu.cui@qq.com" },
]
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
]
keywords = ["pressure-transient-analysis", "feature-extraction", "pattern-recognition", "well-testing", "transient-identification", "Bourdet-derivative", "loglog-plot"]
dependencies = [
    "numpy==2.1.3",
    "pandas==2.2.3",
    "scipy==1.15.0",
    "matplotlib==3.10.1",
    "scikit-learn==1.6.1",
    "scikit-optimize==0.10.2",
    "numba>=0.61.0",
    "plotly>=5.24.1",
    "kneebow==1.0.1"
]
requires-python = ">=3.12"

[project.urls]
Homepage = "https://github.com/vitaliistarr/pta-learn"
Repository = "https://github.com/vitaliistarr/pta-learn.git"
"Bug Tracker" = "https://github.com/vitaliistarr/pta-learn/issues"

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "pytest-cov>=2.0",
    "black>=22.0",
    "isort>=5.0",
    "requests>=2.31.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"] 